# Sermon

I FEEL in such a haste to go out and obey this commandment this morning by compelling those to come in who are now tarrying in the highways and hedges that I cannot wait for an introduction, but must at once set about my business!

Hear then, O you who are strangers to the truth of God as it is in Jesus—hear then the message that I have to bring you! You have fallen, fallen in your father Adam. You have also fallen in yourselves by your daily sin and your constant iniquity! You have provoked the anger of the Most High. And as assuredly as you have sinned, so certainly must God punish you if you persevere in your iniquity, for the Lord is a God of justice and will by no means spare the guilty! But have you not heard; has it not long been spoken in your ears that God, in His infinite mercy, has devised a way whereby, without any infringement upon His honor, He can have mercy upon you, the guilty and the undeserving? To you I speak! And my voice is unto you, O sons of men! Jesus Christ, very God of very God, has descended from heaven and was made in the likeness of sinful flesh! Begotten of the Holy Spirit, He was born of the Virgin Mary. He lived in this world a life of exemplary holiness and of the deepest suffering till, at last, He gave Himself up to die for our sins, “the Just for the unjust, to bring us to God.” And now the plan of salvation is simply declared unto you—“Whoever believes in the Lord Jesus Christ shall be saved.” For you who have violated all the precepts of God and have disdained His mercy and dared His vengeance, there is yet mercy proclaimed, for “Whoever calls upon the name of the Lord shall be saved.” “For this is a faithful saying and worthy of all acceptation, that Christ Jesus came into the world to save sinners, of whom I am chief.” “Whoever comes unto Him, He will in no wise cast out, for He is able also to save unto the uttermost those who come unto God by Him, seeing He ever lives to make intercession for us.” Now, all that God asks of you—and this He gives you—is that you will simply look at His bleeding, dying Son and trust your souls in the hands of Him whose name alone can save from death and hell! Is it not a marvelous thing that the proclamation of this gospel does not receive the unanimous consent of men? One would think that as soon as ever this was preached, “That whoever believes shall have eternal life,” everyone of you, “casting away every man his sins and his iniquities,” would lay hold on Jesus Christ and look alone to His cross. But alas, such is the desperate evil of our nature; such the pernicious depravity of our character that this message is despised—the invitation to the gospel feast is rejected—and there are many of you who are this day enemies of God by wicked works! You are en- emies to the God who preaches Christ to you today—enemies to Him who sent His Son to give His life a ransom for many. Strange, I say, it is that it should be so, yet nevertheless it is the fact and hence the ne- cessity for the command of the text—“Compel them to come in.” Children of God, you who have be- lieved, I shall have little or nothing to say to you this morning. I am going straight to my business—I am going after those who will not come—those who are in the byways and hedges—and God going with me, it is my duty now to fulfill this command, “Compel them to come in.”

First, I must, find you. Secondly, I will go to work to compel you to come in.

### First, I must find you {-}
...
